name: Билд изображения

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получение репозитория
        uses: actions/checkout@v4

      - name: Настройка ноды
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Установка пакетов
        run: npm i --legacy-peer-deps

      - name: Создание изображения
        run: npm run start
        env:
          PUBLIC_ACCESS_TOKEN: ${{ secrets.PUBLIC_ACCESS_TOKEN }}

      - name: Коммит
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add -- . :!package-lock.json && git commit -am "Обновление изображения" && git push -f || echo "No changes to commit"
